### ISSUE TITLE
Loading Oval ROIs on Python 3

### ISSUE THREAD

**Issue by YoshiLucas** [rochefort-lab/fissa#134]
Firstly, thank you for updating FISSA to fix the previous issue that I posted. However, when I updated to the newest version of FISSA, it no longer seemed to work, due to what seems like a threading issue. Since I like to work on multiple things at once, I would ideally like to dedicate half of my CPU to FISSA while I continue working on other things. I probably did something wrong somewhere without realizing it, but I couldn't find the issue (for now) so I thought I'd post an issue. Thank you in advance.

**What I did**

I ran the following code on Python (3.7.7, 64-bit) with Numpy (1.18.1) on Windows 10 (1909) using FISSA 0.7.0:

```
import fissa

rois_location = # ROI zip on local hard drive for our experiment
images_location = # Images on local hard drive for our experiment
output_folder = # Folder on local hard drive

experiment = fissa.Experiment(images_location,rois_location,output_folder)
experiment.separate()
```

I've also run the above code with the number of cores specified as either 8 (half of my cores) or 1 (single-thread).

**What I expected**

I expected FISSA to do its thing like it did before the update.

**What happened**

Python spit out the following error:

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Anaconda3\lib\site-packages\fissa\core.py", line 62, in extract_func
    base_masks = datahandler.rois2masks(rois, curdata)
  File "C:\Anaconda3\lib\site-packages\fissa\datahandler.py", line 83, in rois2masks
    rois = roitools.readrois(rois)
  File "C:\Anaconda3\lib\site-packages\fissa\roitools.py", line 344, in readrois
    mask_frame = np.nonzero(rois[i]['mask'])[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\fissa\core.py", line 389, in separate
    self.separation_prep(redo_prep)
  File "C:\Anaconda3\lib\site-packages\fissa\core.py", line 319, in separation_prep
    results = pool.map(extract_func, inputs)
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
IndexError: index 0 is out of bounds for axis 0 with size 0
```

The above error occurred both when I did and didn't specify the number of cores.

Interestingly, when I ran FISSA with only 1 core, it spit out a shorter error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\fissa\core.py", line 389, in separate
    self.separation_prep(redo_prep)
  File "C:\Anaconda3\lib\site-packages\fissa\core.py", line 324, in separation_prep
    results[trial] = extract_func(inputs[trial])
  File "C:\Anaconda3\lib\site-packages\fissa\core.py", line 62, in extract_func
    base_masks = datahandler.rois2masks(rois, curdata)
  File "C:\Anaconda3\lib\site-packages\fissa\datahandler.py", line 83, in rois2masks
    rois = roitools.readrois(rois)
  File "C:\Anaconda3\lib\site-packages\fissa\roitools.py", line 344, in readrois
    mask_frame = np.nonzero(rois[i]['mask'])[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Update**

I went back and tested fissa with the example files available on GitHub and it worked fine. It must be something on my end, I'll investigate tomorrow in detail after a good night's rest.

**Comment by scottclowe** [comment]
Hi Yoshi,

Thanks for reporting this. This is actually not to do with threading. When you set the number of cores to be 1, multiprocessing is not used at all any more (hence why the error trace is shorter in that case).

This is an issue I found earlier this week. I accidentally broke oval ImageJ rois in #90, which was included in the 0.7.0 release. We did not have any oval rois in the test suite or the example notebook, so the issue was not caught by either of these. Polygon rois are still working fine.

For the moment, please use fissa==0.6.4. There will be a bug fix out soon which will fix loading oval rois.

**Comment by scottclowe** [comment]
Hi again, Yoshi. Version 0.7.1 is now available on pypi, and it should resolve the problem with using roi types other than polygons and rectangles. Let me know whether this resolves your issue!

**Comment by YoshiLucas** [comment]
Ooh that makes so much sense! We were indeed using oval ROIs.

For some reason, version 0.7.1 works with one of our ROI sets, but not the other. They're both zip sets of oval ROIs.

This is the error that comes up:

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Anaconda3\lib\site-packages\fissa\core.py", line 62, in extract_func
    base_masks = datahandler.rois2masks(rois, curdata)
  File "C:\Anaconda3\lib\site-packages\fissa\datahandler.py", line 83, in rois2masks
    rois = roitools.readrois(rois)
  File "C:\Anaconda3\lib\site-packages\fissa\roitools.py", line 331, in readrois
    rois = read_imagej_roi_zip(roiset)
  File "C:\Anaconda3\lib\site-packages\fissa\readimagejrois.py", line 407, in read_imagej_roi_zip
    roi = parse_roi_file(zf.open(name))
  File "C:\Anaconda3\lib\site-packages\fissa\readimagejrois.py", line 338, in _parse_roi_file_py3
    mask[z, left:, top:] = dd <= 1
ValueError: could not broadcast input array from shape (7,9) into shape (1,9)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\fissa\core.py", line 389, in separate
    self.separation_prep(redo_prep)
  File "C:\Anaconda3\lib\site-packages\fissa\core.py", line 319, in separation_prep
    results = pool.map(extract_func, inputs)
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
ValueError: could not broadcast input array from shape (7,9) into shape (1,9)
```

Would it help if I sent you the ROI sets? I'll ask my PI if I would be allowed to share them with you.

**Comment by scottclowe** [comment]
I can't make any sense of this error...
Given how left, top, mask, and dd are defined in https://github.com/rochefort-lab/fissa/blob/58bb53a/fissa/readimagejrois.py#L306-L312 and
https://github.com/rochefort-lab/fissa/blob/58bb53a/fissa/readimagejrois.py#L324-L338, the shape being assignment must by construction be the same shape as 

If you could send the ROI set which is not working, that would be very helpful. I doubt I'll be able to replicate the bug otherwise. Thanks!

**Comment by swkeemink** [comment]
I also can't make sense of it. We would just need the ROIsets, no need to share any actual calcium data, if that helps.

**Comment by scottclowe** [comment]
I figured it out! It must be that the oval overlaps the left-edge of the image, and so `left=-1`. This should be easy to fix.

**Comment by scottclowe** [comment]
Hi Yoshi. I've fixed the issue with oval and ellipse ROIs partially outside the top and left of the image. Please try using version 0.7.2, and you should find these ROIs work correctly now. Let me know whether this resolves your issue.

**Comment by YoshiLucas** [comment]
It's working now. Thank you so much!
