### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by aurallaura** [rochefort-lab/fissa#289]
I am encountering the error after running the below script and getting the error following. The script was working until I had a hard drive failure and had to reinstall everything. I imported FISSA and it says that I have the 1.0.0 installed. I tried importing the 0.5.3 version (using pip install fissa==0.5.3) because the python script I am using was written in 2019 but says there is an issue with the package.

>>> #initiate experiment
>>> exp = fissa.Experiment(tiff_folder,rois_FISSA,output_folder)
>>> exp.separate(redo_prep=True)
Extracting traces:   0%|                                                                                                                   | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/anaconda3/lib/python3.11/site-packages/fissa/core.py", line 1364, in separate
    self.separation_prep(redo_prep)
  File "/Users/anaconda3/lib/python3.11/site-packages/fissa/core.py", line 1259, in separation_prep
    n_roi = len(outputs[0][1])
                ~~~~~~~^^^
IndexError: list index out of range

Is this likely an error with the version of FISSA or something else?

**Comment by nathalierochefort** [comment]
Dear @aurallaura,
see issue #276:  IndexError: list index out of range while doing experiment.separate() #276
for help.
'it appears that the images and roi paths should be sent as a list. Once I did that, the script correctly recognized my items.'
Hope it helps,

**Comment by zloniko** [comment]
I had similar problem. The last message was:
"linearrings: Input operand 0 does not have enough dimensions (has 1, gufunc core with signature (i, d)->() requires 2)"
I downgrade Shapely version from 2.0.4 to 1.8.4: pip install shapely==1.8.4

Everything works now
